FROM osrf/ros:galactic-desktop
RUN apt update && apt install -y python3 python3-pip ros-galactic-tf2-tools ros-galactic-tf-transformations

RUN pip3 install numpy==1.22.4 opencv-python transforms3d scipy open3d
